name: 'Go Test with Coverage'
description: 'Run Go tests with coverage reporting for go-openapi projects'
author: 'go-openapi'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  go-version:
    description: 'Version of Go to use'
    required: false
    default: '1.21'
  working-directory:
    description: 'Working directory for running tests'
    required: false
    default: '.'
  coverage-file:
    description: 'Name of the coverage output file'
    required: false
    default: 'coverage.out'
  test-flags:
    description: 'Additional flags to pass to go test'
    required: false
    default: '-v -race'

outputs:
  coverage-file:
    description: 'Path to the generated coverage file'
    value: ${{ steps.test.outputs.coverage-file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
    
    - name: Run tests with coverage
      id: test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Running Go tests with coverage..."
        go test ${{ inputs.test-flags }} -coverprofile=${{ inputs.coverage-file }} ./...
        echo "coverage-file=${{ inputs.working-directory }}/${{ inputs.coverage-file }}" >> $GITHUB_OUTPUT
        
    - name: Display coverage summary
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "${{ inputs.coverage-file }}" ]; then
          echo "Coverage Summary:"
          go tool cover -func=${{ inputs.coverage-file }} | tail -1
        fi
