name: go-ctrf-json-reporter installer
description: |
  Download the latest vetted version of go-ctrf-json-reporter.

  github.com/ctrf-io/go-ctrf-json-reporter@{version}

author: go-openapi

inputs:
  version:
    description: |
      State explicitly the version to be downloaded.
      
      By default the "auto" value uses the versions configured in "version.yaml"
    required: false
    default: auto

outputs:
  version:
    description: The version of the tool that has been installed
    value: ${{ steps.resolve-version.outputs.version }}

runs:
  using: composite
  steps:
    -
      name: Check if runner is supported
      if: >-
        ${{
          (runner.os != 'Linux' && runner.os != 'macOS' && runner.os != 'Windows') ||
          (runner.os == 'Linux' && runner.arch != 'X64' ) ||
          (runner.os == 'Windows' && runner.arch != 'X64' ) ||
          (runner.os == 'macOS' && runner.arch != 'ARM64')
        }}
      shell: bash
      run: |
          echo "::error::installation not supported for ${{ runner.os }} on ${{ runner.arch }}"
          echo "::error::please build locally with go or see available artifacts at https://github.com/gotestyourself/gotestsum/releases"
          exit 1
    -
      name: Resolve version
      id: resolve-version
      shell: bash
      env:
        TOOL: go-ctrf-json-reporter
        VERSION_RESOLVER: '${{ github.action_path }}/../../get-tool-version.sh'
      run: |
        if [[ '${{ !inputs.version }}' == 'true' || '${{ inputs.version }}' == 'auto' ]] ; then
            VERSION=$("${VERSION_RESOLVER}" "${TOOL}")
        else
          VERSION='${{ inputs.version }}'
        fi

        if [[ -z "${VERSION}" ]] ; then
          echo "::error::Could not resolve version for tool ${TOOL}"
          exit 1
        fi

        echo "::notice title=Version:${VERSION}"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
    -
      name: Install go-ctrf-json-reporter
      shell: bash
      env:
        REPO: github.com/ctrf-io/go-ctrf-json-reporter
        TOOL: go-ctrf-json-reporter
        VERSION: ${{ steps.resolve-version.outputs.version }}
        DOWNLOAD_DIR: ${{ runner.temp }}/downloads
        TARGET_DIR: ${{ github.action_path }}/bin
        GH_TOKEN: ${{ github.token }}
      run: |
        OS=$(echo '${{ runner.os }}'|sed 's/macOS/Darwin/')
        ARCH=$(echo '${{ runner.arch }}'|tr '[A-Z]' '[a-z]'|sed 's/x64/x86_64/')

        mkdir -p "${DOWNLOAD_DIR}"

        ARCHIVE_FORMAT=".tar.gz"
        if [[ "${OS}" == "Windows" ]] ; then
          ARCHIVE_FORMAT=".zip"
        fi

        gh release download "${VERSION}" \
          --repo "${REPO}" \
          --pattern "*_${OS}_${ARCH}${ARCHIVE_FORMAT}" \
          --output "${DOWNLOAD_DIR}"/"artifact${ARCHIVE_FORMAT}"

        if [[ "${OS}" != "Windows" ]] ; then
          (cd "${DOWNLOAD_DIR}" && tar xf "artifact${ARCHIVE_FORMAT}" "${TOOL}" && rm -f "artifact${ARCHIVE_FORMAT}")
        else
          TOOL="${TOOL}.exe"
          (cd "${DOWNLOAD_DIR}" && unzip "artifact${ARCHIVE_FORMAT}" "${TOOL}" && rm -f "artifact${ARCHIVE_FORMAT}")
        fi

        mkdir -p "${TARGET_DIR}"
        mv "${DOWNLOAD_DIR}"/"${TOOL}" "${TARGET_DIR}"

        echo '${{ github.action_path }}/bin' >> "$GITHUB_PATH"

branding:
  icon: 'package'
  color: 'blue'
