name: gotestsum installer
description: |
  Download the latest vetted version of gotestsum.

  gotest.tools/gotestsum@{version}

author: go-openapi

inputs:
  version: string
  required: false
  default: auto

outputs:
  version:
    description: The version of the tool that has been installed
    value: ${{ steps.resolve-version.outputs.version }}

runs:
  using: composite
  steps:
    -
      name: Check if runner is supported
      if: >
        ${{
          (runner.os != "Linux" && runner.os != "macOS" && runner.os != "Windows") ||
          (runner.arch != "X64" && runner.arch != "ARM64")
        }}
      run: |
          echo "::error::installation not supported for ${{ runner.os }} on ${{ runner.arch }}"
          echo "::error::please build locally with go or see available artifacts at https://github.com/gotestyourself/gotestsum/releases"
          exit 1
    -
      name: Resolve version
      id: resolve-version
      shell: bash
      env:
        VERSION_FILE: ${{ github.action_path }}/versions.yml
        TOOL: gotestsum
      run: |
        if [[ '${{ !inputs.version }}' == 'true' || '${{ inputs.version }}' == 'auto' ]] ; then
          VERSION=$(cat "${VERSION_FILE}"|yq ".${TOOL}")
        else
          VERSION='${{ inputs.version }}'
        fi

        if [[ -z "${VERSION}" ]] ; then
          echo "::error::Could not resolve version for tool ${TOOL}"
          exit 1
        fi

        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
    - 
      name: Install gotestsum
      shell: bash
      env:
        REPO: gotestyourself/gotestsum
        DOWNLOAD_DIR: ${{ runner.temp }}/downloads
        TARGET_DIR: ${{ github.action_path }}/bin
        TOOL: gotestsum
        VERSION: ${{ steps.resolve-version.outputs.version }}
      run: |
        OS=$(echo '${{ runner.os }}'|tr '[A-Z]' '[a-z]'|sed 's/macos/darwin/')
        ARCH=$(echo '${{ runner.arch }}'|tr '[A-Z]' '[a-z]')

        mkdir -p "${DOWNLOAD_DIR}"

        gh release download "${VERSION}" \
          --repo "${REPO}" \
          --pattern "*_${OS}_${ARCH}.tar.gz" \
          --dir "${DOWNLOAD_DIR}" \
          --output artifact.tgz

        # should check checksum etc
        (cd "${DOWNLOAD_DIR}" && tar xf artifact.tgz "${TOOL}" && rm -f artifact.tgz)

        mkdir -p "${TARGET_DIR}"
        mv "${DOWNLOAD_DIR}"/"${TOOL}" "${TARGET_DIR}"

        echo '${{ github.action_path }}/bin' >> "$GITHUB_PATH"

branding:
  icon: 'package'
  color: 'blue'
