name: Contributors

permissions:
  contents: read

on:
  schedule:
    - cron: '18 4 * * 6'

  workflow_dispatch:

jobs:
  update-contributors:
    name: all-time contributors
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.create-pull-request.outputs.pull-request-url }}
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    -
      name: Identify all-time contributors to this repository
      uses: github/contributors@4fda46a62ca1f1f1162c053c11d9576ae0cdda99 # v2.0.15
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY:  ${{ github.repository }}
        LINK_TO_PROFILE: 'True'
    -
      name: Rename contributor file
      run: |
        rm -rf contributors.json
        mv contributors.md CONTRIBUTORS.md
    -
      name: Switch to go-openapi bot user
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      with:
        app-id: ${{ secrets.CI_BOT_APP_ID }}
        private-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
    -
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
      with:
        gpg_private_key: ${{ secrets.CI_BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.CI_BOT_GPG_PASSPHRASE }}
        fingerprint: ${{ secrets.CI_BOT_SIGNING_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
    -
      name: Create a PR
      id: create-pull-request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        commit-message: "doc: updated contributors file"
        branch: doc/contributors-bot
        delete-branch: true
        title: "doc: updated contributors file"
        token: ${{ steps.app-token.outputs.token }}
        labels: "bot"
        draft: false
        assignees: fredbi
        reviewers: fredbi
        sign-commits: true
        signoff: true # DCO

  auto-merge:
    # description: |
    #   Validates and merge the pull request triggered above.
    needs: [update-contributors]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{needs.update-contributors.outputs.pull-request-url}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      -
        name: Auto-approve PR
        run: gh pr review --approve "$PR_URL"
      -
        name: Auto-merge PR
        run: gh pr merge --auto --rebase "$PR_URL"
