name: Release

permissions:
  contents: read

# description: |
#   Build a github release on either pushed tag or a manual workflow call.
#
#   At this moment, the only available asset is a release note.

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  gh-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      -
        name: Extract tag message
        id: get-message
        # tag message is not retrieved unless we fetch the ref explictly
        env:
          TAG: ${{ inputs.tag }}
        run: |
          set -x

          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          MESSAGE=$(git tag -l "$TAG" --format='%(contents:subject)

          %(contents:body)
          ')
          export MESSAGE
          {
            echo "message<<EOF"
            printenv MESSAGE
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

          echo "Message in git tag $TAG"
          echo "$MESSAGE"
      -
        name: Generate release notes
        # this uses git-cliff to generate a release note from the commit history
        id: notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPO: ${{ github.repository }}
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          config: '.cliff.toml'
          args: >-
            --current
            --with-tag-message '${{ steps.get-message.outputs.message }}'
      -
        name: Create github release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          body: ${{ steps.notes.outputs.content }}
          tag_name: ${{ inputs.tag }}
          generate_release_notes: false # skip auto-generated release notes from github API
